log_file: "/var/log/sentry.log"
no_alerts: false
run_once: false

smtp:
    server: localhost
    port: 25
    username: ""
    password: ""

defaults:
    interval: 1m
    from_email: "sentry@monitor"
    alert_email: alerts@monitor
    follow_redirects: true
    return_codes: [200]

targets:
  -
    name: "Google"
    url: "https://google.com"
    alert_email: "yoda@gmail.com"
  -
    name: "Yahoo"
    url: "https://www.yahoo.com"
    alert_email: "jarjar@yahoo.com"
    interval: 10s
    follow_redirects: false
    return_codes: [200, 201]
